Merge develop into main
dmitriylmao/WebWeavers pull request #11
Opened 2024-10-31 15:06 UTC by dmitriylmao

_Актуальный деплой_ : https://webweavers001.netlify.app/ru

![Defo_smotrit_na_nebo_S_trubkoy](https://github.com/user-attachments/assets/9c9650f7-2e17-4aa0-a344-b520cecd271a)

2024-10-31 18:06 UTC, Glinsky-Nikita reviewed
Все хорошо, но на компьютерах можно изначально уменьшить масштаб

2024-11-01 09:36 UTC, olya-yevsieienko requested changes
Молодцы, хорошо поработали. Отдельный плюсик за то, что развернули стенд)

Есть всего несколько глобальных вопросов и комментариев. 
1. Везде поправить импорты. Здорово, что вы настроили alias, используйте его всех файлах.
2. Если есть какая-то строка кода или число, например, RU и EN, лучше вынести в глобальные константы. https://ru.hexlet.io/blog/posts/magic-numbers (тут о магических числах, но принцип применим и к строкам).
3. Для чего были созданы FooterMobile, FooterDesctop и т.д? Почему не сделали одним компонентом, для которого меняются стили на разных разрешениях?

2024-11-01 09:36 UTC, olya-yevsieienko commented on .gitignore
> +
Общепринято, что отступы между строками кода равняются одной пустой строке.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +import React from 'react';
Этот комментарий не несет особенной пользы. Лучше его убрать, чтобы не было нагромождения кода. 
Комментарии стоит писать только в особенных случаях. Например, объяснение сложных вычисления, которые помогли бы другому разработчику понять, что происходит; какой-то костыль, который сейчас нельзя исправить, но в будущем необходимо и т.д.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +          </div>
Вот этот код можно сократить. https://ru.react.dev/learn/rendering-lists
Если вдруг дизайнер захочет добавить сюда ещё пункты, то html код станет совсем громоздким)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Banner/Banner.module.css
> +}
При написании стилей лучше придерживаться этих правил https://netology-university.bitbucket.io/codestyle/css/#order.
Не буду дублировать это по всех css файлах. Проверьте, пожалуйста, везде)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Button/Button.js
> +import styles from './Button.module.css'; // Импорт CSS модуля
Комментарии.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Button/Button.js
> +    </Link>
Общепринято, если у тега атрибутов больше трех (а иногда и двух), располагать их в столбик. Это делает код более читабельным.
<img
   src={imgSrc}
   alt="button icon"
   className={styles.buttonImage}
/>

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Button/Button.module.css
> +.buttonImage {
Между классами стоит оставлять одну пустую строку, чтобы код был более читабельным)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +  }, []);
Вот это лучше вынести отсюда, может пригодиться где-то в другом месте. Сделать это отдельным хуком) 
https://react.dev/learn/reusing-logic-with-custom-hooks

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/LanguageSwitcher.js
> +  };
RU и EN лучше вынести в константы, чтобы снизить шанс описки)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/desktop/FooterDesktop.js
> +import LanguageSwitcher from '@/components/Footer/LanguageSwitcher';
Лучше соблюдать такой порядок написания импортов:
Стандартные библиотеки: библиотеки из react, react-dom и других стандартных модулей.
Сторонние библиотеки: пакеты, установленные через npm или yarn (axios, redux и т. д.)
Локальные модули: свои компоненты, утилиты, стили и другие файлы проекта.
Стили/.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/desktop/FooterDesktop.js
> +            </ul>
Здесь тоже лучше использовать рендеринг списков.https://ru.react.dev/learn/rendering-lists

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/desktop/FooterDesktop.js
> +import LanguageSwitcher from '@/components/Footer/LanguageSwitcher';
Если есть alias, нужно использовать их во всех файлах. Должно быть одинаковое написание кода во всех файлах, это намного упрощает в будущем разработку)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Footer/desktop/FooterDesktop.js
> +              </li>
И здесь.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Header/Header.js
> +          </nav>
Рендеринг списков. 
Этот комментарий так же не буду дублировать, проверьте везде, пожалуйста)

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Header/Header.js
> +      {/* Логотип и название */}
Излишние комментарии.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Logo_swiper/Logo_swiper.js
> +  },
Это лучше вынести в файлик constants.js и положить в папке с компонентом.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/ProductCard/ProductsList.js
> +  }, []);
Использовать хук, который вы вынесли из компонента (писала выше).

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/ProductCard/ProductsList.js
> +      volume: '450 мл',
Вынести в отдельный файл.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Promotion_swiper/Promotion_swiper.js
> +const sliderData = [promotionSlide, partnerSlide];
Вынести в отдельный файл.

2024-11-01 09:36 UTC, olya-yevsieienko commented on components/Сategories/Сategories.js
> +                href={category.link}
Лучше избегать объявления констант, рефов и вычислений непосредственно внутри return, поскольку это может привести к потенциальным проблемам с производельностью, читаемостью и логикой обновления состояний.

2024-11-02 15:33 UTC, dmitriylmao commented on .gitignore
> +
Везде исправлено

2024-11-02 15:33 UTC, dmitriylmao commented on components/Banner/Banner.js
> +import React from 'react';
Убраны все ненужные комментарии

2024-11-02 15:35 UTC, dmitriylmao commented on components/Banner/Banner.js
> +          </div>
Конкретно по этому пункту все таки вопрос, выносить это в отдельный массив ,выглядит так же громоздко. Но с остальными <li> согласен.

2024-11-02 15:35 UTC, dmitriylmao commented on components/Banner/Banner.module.css
> +}
Переделано

2024-11-02 15:36 UTC, dmitriylmao commented on components/Logo_swiper/Logo_swiper.js
> +  },
Сделано для всех массивов

2024-11-02 15:37 UTC, dmitriylmao commented on components/ProductCard/ProductsList.js
> +  }, []);
Готово , но футер не исправлял (будет переделываться)

2024-11-02 15:38 UTC, dmitriylmao commented on components/Сategories/Сategories.js
> +                href={category.link}
Вот тут я не понимаю , как это вынести до первого return'а

2024-11-03 06:50 UTC, olya-yevsieienko reviewed
Ещё одна деталь, которую обсуждали в пятницу)

Во все папки с компонентами нужно добавить файл index.js, который будет импортировать всё из файла с компонентом. 
Тогда испорт вместо такого:
import ProductsList from '../components/ProductCard/ProductsList';
Станет таким:
import ProductsList from '../components/ProductCard';

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +          <button className={styles.catalogButton}>В КАТАЛОГ</button>
Вижу, что в папке components есть Button. Вынести её в папку UI и подключить везде.
Получается, что во всех местах, где есть кнопка, ей прописываются стили. Не нужно их дублировать.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +          </div>
https://trycode.pw/c/RQZ8V
Нужно доработать, но суть, надеюсь понятна. 
Выглядеть громоздко не будет. То, что можно сократить, лучше сокращать)

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Banner/Banner.module.css
> +  z-index: 2;
Почему именно два? Изменила на один, всё работает так же)
С z-index лучше быть аккуратными и не писать рандомные числа.

Если есть необходимость, можно создать переменные для z-index.
// Z-index
$ui-index-minus-1: -1;
$ui-index-0: 0;
$ui-index-1: 1;
$ui-index-2: 2;
$ui-index-3: 3; // Menu
$ui-index-4: 4; // Modal window
$ui-index-5: 5; // Elements that overlap everything

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Banner/Banner.module.css
> +    line-height: 19.8px;
Все числа должны быть целыми.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Button/Button.js
> +    </Link>
Вот это важно. 
Кнопка должна быть кнопкой всегда. Во вчерашнем документе я приложила пример компонента кнопки. Лучше передавать её пропс onClick, который по дефолту может быть () => {}.
Если эта кнопка используется для роутинга, то можно сделать так:
  <Link href={`/какой-то роут`}>
    <Button label="Каталог" />
  </Link>

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Logo_swiper/Logo_swiper.js
> +export default function Logo_swiper() {
Правильно назвать компонент  LogoSwiper. Каждое слово с большой буквы.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Logo_swiper/Logo_swiper.js
> +              <div className={styles.card}>
Для ключей лучше не использовтаь индексы. 
https://sacret.medium.com/индекс-в-качестве-ключа-анти-паттерн-56bab8ada309

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/ProductCard/ProductCard.js
> +        <p className={styles.volume}>
Link лучше вынести отсюда. Может, где эта карточка не будет вести на страницу товара. 
Первый div лучше заменить на article.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/ProductCard/ProductCard.js
> +              src={volumeType}
Зачем пустые строки?)

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/ProductCard/ProductCard.js
> +          </button>
Тут UI Button.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/ProductCard/ProductsList.module.css
> +.highlight {
Отступы.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Promotion_swiper/Promotion_swiper.js
> +export default function Promotion_swiper() {
Promotion_swiper =>  PromotionSwiper.
Заменить во всех местах.

2024-11-03 06:50 UTC, olya-yevsieienko commented on components/Сategories/Сategories.js
> +                href={category.link}
Есть два варианта: либо использовать ref для всех категорий, либо сделать компонент Category и к нему применять анимации.
Category.jsx положить в папку Categorues.

2024-11-03 06:50 UTC, olya-yevsieienko commented on pages/index.js
Тут тоже нужно импорты поправить)

2024-11-04 16:32 UTC, dmitriylmao commented on components/Banner/Banner.js
> +          <button className={styles.catalogButton}>В КАТАЛОГ</button>
Заменены все кнопки на отдельный компонент YellowButton

2024-11-04 16:33 UTC, dmitriylmao commented on components/Banner/Banner.module.css
> +    line-height: 19.8px;
Исправил , где это необходимо. 
В данном случае наверно лучше оставить дробное значение
transition: background-color 0.3s ease;

2024-11-04 16:35 UTC, dmitriylmao commented on components/Logo_swiper/Logo_swiper.js
> +              <div className={styles.card}>
исправлено , отказался от shortid .Просто где это необходимо , создал каждому объекту свой id

2024-11-07 13:53 UTC, dmitriylmao commented on components/Banner/Banner.js
> +            {bannerAdvantages.map((advantage) => (
Смотрю как это работает

2024-11-20 05:59 UTC, olya-yevsieienko requested changes
Молодцы, хорошая работа)

2024-11-20 05:59 UTC, olya-yevsieienko commented on .gitignore
> +.idea
В гитигноре, но в pr есть)

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +  return (
```suggestion
  const { t } = useTranslation('common');
 
  return (
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +import { useTranslation } from 'next-i18next';
Порядок поключения импортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +          </h3>
Иным способом можно написать?

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Breadcrumb/Breadcrumb.js
> +  ];
Это лучше вынести в отдельно и передавать через пропсы, хлебные крошки будут на всех страницах.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Breadcrumb/Breadcrumb.module.css
> +.breadcrumb {
Почему css?
Для страницы товара договорились, что будет scss и определенная стилистика написания.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +          <h2 className={styles.mainTitle}>{t('MainTitle')}</h2>
Здесь лучше h1 использовать.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Banner/Banner.js
> +                <span className={styles.icon}>+</span>
Вот этот плюсик лучше сделать через псевдоэлемент.
В верстке лучше по максимуму сокращать количество элементов, которые относятся только к дизайну, по возможности создавать их с помощью css. 

```suggestion
                <span className={styles.icon} />
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Breadcrumb/Breadcrumb.module.css
> +}
Перенести медиа, как договаривались на занятии. 
Брейкпоинты задать с помощью переменных.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Button/Button.js
> +const Button = ({ text, href, imgSrc, customClass }) => {
Почему есть этот компонент Button и YellowButton? Чем они отличаются?

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/EmailInput.js
> +        <span>&#9654;</span>
Это лучше сделать иконкой)

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +            </li>
Рендеер списков.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +            </li>
Рендер списков.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +              <>
React фрагмент нужен, если нет одной общей обертки для блоков. Тут он не нужен.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +                    download="./EmailInput.js"
А что тут скачивается?)

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.module.css
> +  color: var(--white_lightGray-footerText);
Нужно именовать переменные в lower case и kebab case.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.module.css
> +.contactsContainer {
Нужно придерживаться одного подхода в именовании классов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.module.css
> +  text-decoration-style: solid;
Solid вроде и так будет по дефолту.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.module.css
> +    text-decoration-style: solid;
Можно и тут убрать.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/Footer.module.css
> +@media (max-width: 480px) {
Все брейкпоинты должны браться из переменных.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/LanguageSwitcher.js
> +    const newLanguage = language === 'ru' ? 'en' : 'ru';
Вынести ru  и en в глобальные константы.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Footer/LanguageSwitcher.js
> +
Можно упростить.
В глобальных константах будет 
export const APP_LANGUAGE = {
  RU: 'ru',
  EN: 'en',
};

```suggestion
  const isRussian = language === 'ru';
  const currentFlag = isRussian ? rusFlag : ukFlag;

  const gradients = {
    APP_LANGUAGE.RU:
      'linear-gradient(15deg, rgba(255, 0, 0, 0.3) , rgba(38, 128, 212, 0.3),rgba(255, 255, 255, 0.3))',
    APP_LANGUAGE.EN:
      'linear-gradient(-15deg, rgba(38, 128, 212, 0.3), rgba(255, 255, 255, 0.3), rgba(255, 0, 0, 0.3))',
  };

```

И там, где нужен градиент, брать его как gradients[language] .

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +import { useTranslation } from 'next-i18next';
Порядок испортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +            </a>
Рендер списков.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +        <div className={styles.headerLine}></div>
Можно линию сделать с помощью border или псевдоэлементом, чтобы не добавлять в разметку тег.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +            <div className={styles.itemCount}>3</div>
Это лучше сделать span.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +                <span className={styles.mainText}>opt.sultan@mail.ru</span>
Input type email.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/Header.js
> +                  alt="Иконка телефона"
Alt тоже должен быть с переводом.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/SearchInput.js
> +
Порядок подключения импортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/SearchInput.js
> +    <div className={styles.container}>
```suggestion
export default function SearchInput() {
  const { t } = useTranslation('common');
  
  return (
    <div className={styles.container}>
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/SearchInput.js
> +        </span>
А зачем здесь обертка span?

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Header/SearchInput.module.css
> +  background-color: var(--yellow_lightPurple-button);
Переименовать переменную как писала выше.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/LogoSwiper/Constants.js
> +  //{ src: '/images/Logo_swiper/logo7.png', alt: 'Logo 7', name: 'Brand 7', number: '007' }//
Если не нужно, то лучше удалить.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/LogoSwiper/LogoSwiper.js
> +import { useTranslation } from 'next-i18next';
Порядок подключения импортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/LogoSwiper/LogoSwiper.js
> +  return (
```suggestion
export default function LogoSwiper() {
  const { t } = useTranslation('common');
  
  return (
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/LogoSwiper/LogoSwiper.module.css
> +  height: 77px;
```suggestion
  height: 78px;
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/LogoSwiper/LogoSwiper.module.css
> +  max-height: 77px;
Ширина, высота и  отступы должны делаться на 4.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Map/Map.js
> +import { useTranslation } from 'next-i18next';
Порядок покдлючения импортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Map/Map.module.css
> +  width: 735px;
Ширина, высота и отступы должны делаться на 4.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCard/Constants.js
> +  },
в модели должны быть поля ru и en.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCard/ProductCard.js
> +        <span className={styles.productBrand}>{brand}</span> {title}
```suggestion
        <span className={styles.productBrand}>{brand}</span>
        {title}
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCardDetails/ProductDetails.js
> +  const [position, setPosition] = useState({ top: '0%', left: '50%' });
useState поднять в другим useState.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCardDetails/ProductDetails.js
> +    <div className={style.container}>
```suggestion
  const openGitHub = () => {
    window.open('https://github.com/dmitriylmao/WebWeavers', '_blank');
  };
  
  return (
    <div className={style.container}>
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCardDetails/ProductDetails.js
> +                style={{ textDecoration: 'none', color: 'inherit' }}
Все стили должны быть в фале стилей, не инлайновыми.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCardDetails/ProductDetails.js
> +                {isDescriptionOpen ? '▴' : '▾'}
Это сделать иконками)

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductCardDetails/ProductDetails.js
> +            </motion.p>
Вынести в отдельный компонент.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductList/ProductsList.js
> +    <section className={styles.container}>
```suggestion
  const { isMobile, isTablet } = useWindowSize();
  const { t } = useTranslation('common');
  
  return (
    <section className={styles.container}>
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/Product/ProductList/ProductsList.module.css
> +@media (min-width: 481px) and (max-width: 768px) {
Все брейкоинты брать из переменных. Проверить во всех файлах.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/PromotionSwiper/PromotionSwiper.js
> +
Порядок подключения импортов.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/PromotionSwiper/PromotionSwiper.js
> +const sliderData = [promotionSlide, partnerSlide];
Это можно вынести в файл с константами.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/PromotionSwiper/PromotionSwiper.js
> +  return (
```suggestion
export default function PromotionSwiper() {
  const { t } = useTranslation('common');
  
  return (
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/PromotionSwiper/PromotionSwiper.module.css
> +  color: var(--yellow_lightPurple-button);
Числа делятся на 4, переменную переименовать.

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/UI/SwitchThemeButton/SwitchThemesButton.module.css
> +.toggle_container {
```suggestion
.toggleСontainer {
```

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/UI/YellowButton/YellowButton.js
> +const YellowButton = ({
Почему yellow? А если дизайнер добавит вторую вариации кнопки с другим цветом? 
У вас уже есть фиолетовая кнопка в темной теме)

2024-11-20 05:59 UTC, olya-yevsieienko commented on components/UI/YellowButton/YellowButton.js
> +  }
Договаривались на занятии, что кнопка будет кнопкой, которой мы передаем нужные действия.

2024-11-20 05:59 UTC, olya-yevsieienko commented on core/constants/index.js
> +export const LANGUAGE_RU = 'ru';
Константы вынесли, но в переключателе языков не используете их)

2024-11-20 05:59 UTC, olya-yevsieienko commented on pages/404.js
> +};
🔥

2024-11-20 05:59 UTC, olya-yevsieienko commented on public/images/444.jpg
![image](https://github.com/user-attachments/assets/39b37536-ddf5-4edc-952f-40dd5adc0ca9)
Очень долго грузится сайт, нужно оптимизировать картинки.

2024-11-24 14:48 UTC, dmitriylmao commented on components/Product/ProductCard/ProductCard.js
> +        <span className={styles.productBrand}>{brand}</span> {title}
Выглядит странно , но это нужно для пробела между брэндом и названием. Можно сделать с новой строки , но тогда придется добавлять {' '}

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Banner/Banner.module.css
> +@media (max-width: 1024px) {
Все брейкпоинты должны браться из переменных.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Banner/Banner.module.css
> +@media (max-width: 768px) {
Все брейкпоинты должны браться из переменных. Во всех файлах)

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Breadcrumb/Breadcrumb.js
> +const Breadcrumb = ({ breadcrumbItems = [] }) => {
Получается не совсем логично. Компонент называется Breadcrumb, но на мобильном их нет, там кнопка. 
Лучше разделить на разные компоненты. Это нормально, если какой-то компонент занимает 10 строк кода)

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Breadcrumb/Breadcrumb.module.scss
> +  @media (max-width: 1280px) {
Брейкпоинты.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Description/Description.js
> +const Description = ({ title, text }) => {
Лучше назвать этот компонент аккордеоном. И добавить children.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Description/Description.js
> +        animate={{ opacity: isOpen ? 1 : 0 }}
const contentConfig = useMemo(() => {
        return {
            visibility: 'visible',
            opacity: isOpened ? 1 : 0,
            transform: `translateY(${isOpened ? 0 : 10}px)`,
            transitionEnd: {
                visibility: isOpened ? 'visible' : 'hidden',
            }
        };
    }, [isOpened]);

Лучше сделать как-то так. В animate передать конфиг, тогда не потребуется  писать так:
if (contentRef.current) {
      setMaxHeight(isOpen ? contentRef.current.scrollHeight : 0);
    }

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Description/Description.js
> +          {isOpen ? '▴' : '▾'}
Иконки, а не символы.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Description/Description.module.scss
> +    color: var(--yellow-hover);
```suggestion
  }
  
  &Title:hover {
    color: var(--yellow-hover);
```

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +import styles from '@/components/Footer/Footer.module.css';
Порядок подключения импортов. Можно не в алфавитном порядке)

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +            ) : null}
Можно ведь это делать с помощью css, а не js.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Footer/Footer.js
> +            )}
Использовать для таких целей стили везде.

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Header/Header.js
> +    }
```suggestion
    document.body.style.overflow = menuOpen ?  'hidden' : '';
```

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Header/Header.js
> +      <div className={styles.MobileContainer}>
Нужно использовать для этих целей стили, а не дублировать верстку)

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/Product/ProductList/SimilarProducts.js
> +import styles from '@/components/Product/ProductList/ProductsList.module.css';
Порядок импортов)

2024-12-07 15:32 UTC, olya-yevsieienko commented on components/UI/CustomButton/CustomButton.js
> +  }
Можно просто передавать нужные пропсы, и при этом кнопка будет оставаться кнопкой)

2024-12-07 15:32 UTC, olya-yevsieienko commented on pages/404.js
> +  const videos = ['/videos/gosling1_mobile.mp4', '/videos/gosling2_mobile.mp4'];
💔

2024-12-25 11:19 UTC, merged